site_name: Campus DC++ Guide

theme:
  name: material
  palette:
    scheme: slate      
    primary: black
    accent: lime       
  features:
    - content.code.copy
    - navigation.tabs

nav:
  - Windows Guide: windows.md
  - macOS Guide: mac.md
  - Linux Guide: linux.md