site_name: Campus DC++ Guide

theme:
  name: material
  palette:
    scheme: slate      
    primary: black
    accent: lime       
  features:
    - content.code.copy
    - navigation.tabs


nav:
  - Welcome Page: index.html               
  - Windows Guide: docs/windows.md
  - macOS Guide: docs/macOS.md
  - Linux Guide: docs/linux.md